rancher/os-services

u/ubuntu-console.yml

Pulling older version in Rc3 causes CA certs to fail.

Updated for rc3 candidate.

---

d/debian-console.yml
u/ubuntu-console.yml

update services to use new service ordering
use `io.rancher.os.after: dep1,dep2` label instead of links

update services to use new service ordering

---

r/resize-fs.yml

The FORCE environment var was added in rancher/os-images#47
but was missing in the service definition

Fix missing FORCE environment var

---

c/centos-console.yml
d/debian-console.yml
f/fedora-console.yml
u/ubuntu-console.yml

`wait-for-network` was removed as of rancher/os#958

Replace wait-for-network with network

---

index.yml
o/open-vm-tools.yml

Depends on rancher/os-images#89
Adds a system service for `open-vm-tools`. Based on Alpine since the package is up to date and it saves us from having to build it ourselves.
Guest info functionality seems to be working in Fusion and Docker Machine with the Fusion driver. Soft power operations still need some wiring to work properly.
rancher/os#219

open-vm-tools service

---

a/amazon-ecs-agent.yml

This allows the ECS agent version to be customized using environment variable interpolation (default is still `latest`). For example, the version can be set to `v1.7.1` with the following in a cloud config:
```
rancher:
environment:
- ECS_AGENT_VERSION=:v1.7.1
```
The colon in the value is unfortunate, but it's necessary since there isn't currently a way to specify default values for environment variables in Compose files.
Ping @JasonSwindle
rancher/os#777

Allow ECS agent version to be customized

---

k/kernel-headers-system-docker.yml
k/kernel-headers.yml

Add ros to kernel header services

---

index.yml

xfce makes more sense as a console than it does as a service. Having it as both will probably cause some confusion.

xfce should only be available as console

---

k/kernel-extras.yml
k/kernel-headers-system-docker.yml
k/kernel-headers.yml

Since the assets for these are now embedded in the images themselves, these attributes aren't needed anymore.

Remove unnecessary fields from kernel extras/headers

---

images/10-alpineconsole/Dockerfile
images/10-centosconsole/Dockerfile
images/10-fedoraconsole/Dockerfile

We're actually using `agetty` now, so this symlink is no longer necessary. Looking back, I think there was a better method than symlinking this anyways.

Remove getty symlink

---

images/20-zfs/Dockerfile
images/20-zfs/Dockerfile.zfs-tools
images/20-zfs/build.sh
images/20-zfs/dev.sh
images/20-zfs/wonka.sh
index.yml
z/zfs.yml

there will be a docs PR in the rancher/os repo to go with this
So far, i've been working with 0.7.1, so there's more work to go
basically
```
ros service enable zfs
ros service up zfs
```
will git clone zfsonlinux, and then build it for the currently running kernel
it'll then build a new zfs-tools image, and then system-docker cp wonka's for each file in bin&sbin into the console.
> *NOTE:* atm, I'm using the dev HEAD of the git repo, because that's what builds on the 4.9 kernel - that will change as time goes on.
TODO (some in a later PR):
LATER

WIP: Zfs service

---

index.yml

Docker 1.13.0 is not available as service yml, currently docker 1.13.1 is available only.
Fixes rancher/os#1607

Use the correct docker 1.13.X version in index.yml

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
images/20-zfs/wonka.sh
u/ubuntu.yml
x/xfce.yml

https://github.com/rancher/os/issues/1615
I presume to v0.9.0 these should be moved to a `media-volumes`  which gets added to `all-volumes` - kinda surprising that this wasn't an issue in 0.7.

add /mnt and /media shared mounts to the consoles

---

images/20-zfs/build.sh

if the build is interrupted and re-ran, the build.sh script tries to move the spl-{version} directory (not just it's contents) inside of directory spl, instead of renaming it to spl, so you get spl/spl-{version}. this stops the build in it's tracks no matter how many times it is restarted. this commit makes it so the contents of spl-{version} are simply moved on top of spl if it already exists, or renames spl-{version} to spl as intended if not.

fix zfs build mv failure

---

a/amazon-metadata.yml
images/20-amazon-metadata/Dockerfile
images/20-amazon-metadata/README.md
images/20-amazon-metadata/ec2-metadata/ec2-metadata.sh
images/20-amazon-metadata/ec2-metadata/ec2-tag-to-env.sh
images/20-amazon-metadata/ec2-metadata/ec2-tags.sh
images/20-amazon-metadata/ec2-metadata/set-config.sh
images/20-amazon-metadata/entry.sh
images/20-volume-netshare/Dockerfile
images/20-volume-netshare/README.md
index.yml
v/volume-cifs.yml
v/volume-efs.yml
v/volume-nfs.yml

Fixes rancher/os#1775
Added new services:
Fetches Amazon AWS metadata and some other data (see [README](images/20-amazon-metadata/README.md)) and puts them to config.
Volume driver for network volumes: https://github.com/ContainX/docker-volume-netshare
Added system services for each volume type:
* volune-efs
* volume-cifs
* volume-nfs
See [README](images/20-volume-netshare/README.md) for details.

Added volume-netshare drivers and AWS metadata provider

---

i/iscsi.yml
images/20-iscsi/Dockerfile
images/20-iscsi/Dockerfile.iscsi-tools
images/20-iscsi/build.sh
images/20-iscsi/entry.sh
images/20-iscsi/wonka.sh
index.yml

It installs, but I haven't set up an iSCSI target and tested that yet.
testing with https://wiki.archlinux.org/index.php/TGT_iSCSI_Target

Add open-iscsi support

---

a/amazon-ecs-agent.yml

Maps the ecs-agent credentials metadata port 51679 back to the ecs-agent container
This change is required in order to enable task iam roles as per : http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#enable_task_iam_roles

Update amazon-ecs-agent to expose 51679

---

images/20-zfs/build.sh

This would allow one to specify a test version of spl/zfs and have it work. i.e. `0.7.0-rc4`.
Test versions are otherwise extracted folders without `-rc4` part which would make the `mv` command fail, so extracting straight into `spl` and `zfs` will work around that problem.

Fix spl and zfs extraction

---

v/volume-cifs.yml

This PR fixed a wrong configure in the volume-cifs service. The docker-volume-netshare's base path is /mnt, but the service's volume mount is /mnt/volumes/netshare/cifs:/mnt, So that other containers cannot find cifs volume correct path.

Fixed volume-cifs mount fail

---

images/20-zfs/Dockerfile
images/20-zfs/build.sh

In order to adapt to changes in the kernel using gcc 7.3 to compile the zfs modules
https://github.com/rancher/os/issues/2240

Update spl and zfs to 0.7.5

---

c/crontab.yml

This sets container crontab version to 0.4.0 and Docker
API version 1.22 (1.10.3).

Update container crontab version

---

images/20-zfs/Dockerfile
index.yml
z/zfs.yml

Relate to this PR: https://github.com/rancher/os-kernel/pull/61
The `libelf-dev` should be installed.

Enable ZFS

---

a/amazon-ecs-agent.yml

According the [ecs docs:](https://github.com/aws/amazon-ecs-agent/blob/master/README.md#persistence)
1. `ecs` directory change to `/opt/var/lib/ecs`
2. `ecs-agent` need configure `ECS_HOST_DATA_DIR` environment
> `ECS_HOST_DATA_DIR` is to determine the source mount path for container metadata files in the case the ECS Agent is running as a container. The default value is `/var/lib/ecs`, so I think this also needs to be  changed
rancher/os#2394

Change ecs directory

---

images/20-zfs/build.sh

Signed-off-by: Jerome Doucerain <jerome.doucerain@bell.ca>
In case we want to enable and use the RancherOS zfs service when RancherOS is running behind a web proxy, the zfs-tools build command (system-docker build --network=host -t zfs-tools arch/) has to take into account the http_proxy, https_proxy and no_proxy environment variables.
So the pull request is meant to bring the required environment variables to the zfs-tools build command

add http proxy environment variables to zfs-tools build context

---

images/10-virtualboxtools/Dockerfile
images/10-virtualboxtools/run
index.yml
v/virtualbox-tools.yml

https://github.com/rancher/os/issues/143
First, you need to start the `virtualbox-tools` service in rancheros.
```
sudo ros service enable virtualbox-tools
sudo ros service up virtualbox-tools
```
> Note: if you switch consoles, you may need to re-run `ros service restart virtualbox-tools`.
After the `virtualbox-tools` service starts, it will automatically load the vbox module and start the `VBoxService` process.
```
lsmod | grep -i vbox
vboxsf                 49152  0
vboxguest             258048  2 vboxsf
ps -ef | grep VBoxService
root      1898     1  0 09:12 ?        00:00:00 [VBoxService] <defunct>
root      1900     1  0 09:12 ?        00:00:00 /sbin/VBoxService --disable-automount
```
At this point, you can mount the shared folder with `mount.vboxsf test /mnt`. If you want to mount …

Add virtualbox-tools support

---

images/10-vboxtools/Dockerfile
v/virtualbox-tools.yml

1.  Upgrade vbox version to 5.2.26
2. Fix virtualbox-tools failed to start
```
VBoxService: error: VbglR3Init failed with rc=VERR_FILE_NOT_FOUND
```

Upgrade vbox version to 5.2.26 and fix VBoxService failed to start

---

Dockerfile.dapper
images/10-alpineconsole/Dockerfile
images/10-selinuxtools/prebuild.sh
images/20-amazonenadriver/Dockerfile
images/20-iscsi/Dockerfile.iscsi-tools
images/20-zfs/Dockerfile.zfs-tools
scripts/build-images

These are some fixes for build errors I had in os-services:
build-image build() function should use return not continue 
02-console/update-keys does not exist - remove its use
can not use apt-update on Dockerfiles based on ubuntu 17.04 anymore use ubuntu 17.10 instead

fixes for some build errors in os-services

---

images/20-iscsi/build.sh

Enabling the `open-iscsi` service on RancherOS didn't work due to this line, not giving to the build context the appropriates proxy variables.
It didn't work giving upper-case env var, this is why we have a lower-case as key and upper-case reference as value.
We can't let a lower-case reference as value because the [service definition](https://github.com/rancher/os-services/blob/ce870f9e95357e31f520ac2a21936edc16ebe75c/o/open-iscsi.yml#L11) takes only upper-case proxy variables.

[open-iscsi] Fix proxy not forwarded to build

---

images/10-openvmtools/Dockerfile

```
Package libtirpc1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
libtirpc-common
E: Package 'libtirpc1' has no installation candidate
```

Fix openvmtools build deps

---

images/20-amazonmetadata/Dockerfile

Fixes a broken build preventing a release to address an unrelated CVE.

images: pin amazon-metadata to alpine 3.11
