u/ubuntu-console.yml

bump ubuntuconsole:v0.3.1

---

d/debian-console.yml
index.yml

really add debian:jessie console
the one built with this: rancherio/os#218

debian-console

---

u/ubuntu-console.yml

Reverts rancherio/os-services#8

Revert "bump ubuntuconsole:v0.3.1"

---

k/kernel-headers-system-docker.yml
k/kernel-headers.yml

Depends on rancher/os-images#92
rancher/os#1053

Allow kernel headers URL to be configurable

---

o/open-vm-tools.yml

Based on comments in https://github.com/rancher/os-images/pull/100

Add command and system volumes to open-vm-tools, to enable soft power operations

---

a/amazon-ecs-agent.yml

Run ECS agent in User Docker

---

index.yml

1.12.3 engine should be in the list

---

index.yml

List only one 1.12 Docker engine release

---

index.yml

show only one 1.12 Docker engine release

---

c/centos.yml
d/debian.yml
f/fedora.yml
k/kernel-extras.yml
k/kernel-headers-system-docker.yml
k/kernel-headers.yml
o/open-vm-tools.yml
u/ubuntu.yml
x/xfce.yml

use the new tags for the 0.7.1 images

---

a/alpine.yml
index.yml

Signed-off-by: Sven Dowideit SvenDowideit@home.org.au
for https://github.com/rancher/os/issues/1151
needs https://github.com/rancher/os-images/pull/108 to be merged and published first.

Add an alpine console

---

k/kernel-extras.yml
k/kernel-headers-system-docker.yml
k/kernel-headers.yml

use new kernel tags for 4.8.7

---

k/kernel-extras-4.8.7-rancher.yml
k/kernel-extras-4.9-rc6-rancher.yml
k/kernel-extras-4.9-rc6-rancher2.yml
k/kernel-headers-4.8.10-rancher.yml
k/kernel-headers-4.8.7-rancher-system-docker.yml
k/kernel-headers-4.8.7-rancher.yml
k/kernel-headers-4.9-rc6-rancher-system-docker.yml
k/kernel-headers-4.9-rc6-rancher.yml
k/kernel-headers-4.9-rc6-rancher2-system-docker.yml
k/kernel-headers-4.9-rc6-rancher2.yml

This is probably something we could validate somewhere.

The servicename must match the filename

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
o/open-vm-tools.yml
u/ubuntu.yml
x/xfce.yml

use the 0.8.0-rc1 images

---

index.yml
k/kernel-extras.yml
k/kernel-headers-system-docker.yml
k/kernel-headers.yml

now to decide where to set that env var.

Add a kernel-headers alias to install the running kernel-headers version

---

Dockerfile.dapper
d/docker-1.12.5.yml
images/10-docker-1.12.5/Dockerfile
images/10-docker-1.12.5/prebuild.sh
images/10-docker-1.12.5_arm/Dockerfile
images/10-docker-1.12.5_arm/prebuild.sh
images/10-docker-1.12.5_arm64/Dockerfile
images/10-docker-1.12.5_arm64/prebuild.sh

I've built the images and pushed them, but haven't had time to test yet
arm and arm64 docker was built and released to https://github.com/rancher/docker-package/releases

Add Docker 1.12.5 release

---

d/docker-1.12.6.yml

update to use new cmdline

---

images/20-zfs/build.sh

don't hardcode for 4.9.2

---

Dockerfile.dapper
d/docker-1.13.0.yml
images/10-docker-1.13.0/Dockerfile
images/10-docker-1.13.0/prebuild.sh
index.yml

try it out with 
```
ros config set rancher.repositories.testj.url https://raw.githubusercontent.com/SvenDowideit/os-services/docker-1.13
```

WIP - don't merge: test out Docker 1.13.0-rc7

---

a/alpine.yml
images/10-alpineconsole/Dockerfile

fix alpine console rancher user lockout

---

images/20-zfs/Dockerfile
images/20-zfs/Dockerfile.zfs-tools
images/20-zfs/build.sh
images/20-zfs/entry.sh
images/20-zfs/wonka.sh
z/zfs.yml

More fix zfs

---

images/20-zfs/build.sh
images/20-zfs/entry.sh
images/20-zfs/wonka.sh
z/zfs.yml

Some small cleanups

---

o/open-vm-tools.yml

fix for https://github.com/rancher/os/issues/1543

add the ros entrypoint to fix the shutdown/suspend scripts

---

z/zfs.yml

Add the PROXY env to the zfs service

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
o/open-vm-tools.yml
u/ubuntu.yml
z/zfs.yml

v0.9.2 release

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
o/open-vm-tools.yml
u/ubuntu.yml
z/zfs.yml

RancherOS v1.0.0

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
o/open-vm-tools.yml
u/ubuntu.yml
z/zfs.yml

update images for v1.0.1

---

index.yml
r/rancher-server-stable.yml
r/rancher-server.yml

add Rancher-server as a dev test service

---

Dockerfile.dapper
d/docker-17.05.0-ce.yml
images/10-docker-17.05.0-ce/Dockerfile
images/10-docker-17.05.0-ce/prebuild.sh
index.yml

Add Docker v17.05.0-ce

---

images/10-openvmtools/Dockerfile
o/open-vm-tools.yml

add docker user to open-vm-tools and add sudo so it can work in machine

---

o/open-vm-tools.yml

Use the latest image for testing

---

images/10-docker-1.12.6_arm/prebuild.sh
images/10-docker-17.03.1_arm/prebuild.sh
images/10-docker-17.04.0_arm/prebuild.sh
images/10-docker-17.05.0_arm/prebuild.sh

fix ARM32 engine images

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
u/ubuntu.yml
z/zfs.yml

update master with v1.0.2 image names

---

d/docker-17.06.0-ce.yml
index.yml

this needs to go into `v1.1.0-rc2` and `v1.0.4`

add docker 17.06-ce

---

images/10-centosconsole/Dockerfile
images/10-fedoraconsole/Dockerfile

Add ip cmd for docker-machine

---

o/open-vm-tools.yml

use the open-vm-tools version number in the image tag

---

images/20-zfs/build.sh

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.0

Use version 0.7.0 of zfs and spl

---

images/20-zfs/Dockerfile.zfs-tools

for https://github.com/rancher/os/issues/1976

Add python to zfs-tools image so arcstat.py works

---

images/20-zfs/build.sh

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.1

Update spl and zfs to 0.7.1

---

d/docker-17.06.1-ce.yml
images/10-docker-17.06.1/Dockerfile
images/10-docker-17.06.1/prebuild.sh
images/10-docker-17.06.1_arm/Dockerfile
images/10-docker-17.06.1_arm/prebuild.sh
index.yml

update amd64 and arm32 docker 17.06.1

---

Makefile
images/10-openvmtools/Dockerfile
o/open-vm-tools.yml

open-vm-tools-10.1.10-2 - 10.1.5 wasn't working

---

d/docker-17.09.1-ce.yml
images/10-docker-17.09.1/Dockerfile
images/10-docker-17.09.1/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2152

Add docker-17.09.1-ce

---

a/amazon-ena-driver.yml
images/20-amazonenadriver/Dockerfile
images/20-amazonenadriver/build.sh
index.yml

https://github.com/rancher/os/issues/2160

Add aws ena driver

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
images/10-alpineconsole/Dockerfile
images/10-centosconsole/Dockerfile
images/10-debianconsole/Dockerfile
images/10-fedoraconsole/Dockerfile
images/10-ubuntuconsole/Dockerfile
u/ubuntu.yml

https://github.com/rancher/os/issues/2193

Upgrade each console image to v1.2.0-rc1

---

d/docker-17.12.1-ce.yml
images/10-docker-17.12.1/Dockerfile
images/10-docker-17.12.1/prebuild.sh
images/10-docker-17.12.1_arm64/Dockerfile
images/10-docker-17.12.1_arm64/prebuild.sh
index.yml

I've copied these bits from the 17.12.0 references -- if that's not right, I'm happy to adjust. :+1:

Add Docker 17.12.1

---

images/10-qemuguestagent/Dockerfile
index.yml
q/qemu-guest-agent.yml

Add qemu-guest-agent service for RancherOS.
fix issue https://github.com/rancher/os/issues/2267

add qemu-guest-agent service

---

images/20-nvidiadriver/Dockerfile
images/20-nvidiadriver/build.sh
images/20-nvidiadriver/ubuntu-build.sh
index.yml
n/README.md
n/nvidia-driver.yml

Deal with [rancher/os#1637](https://github.com/rancher/os/issues/1637#event-1549138381)

add nvidia-driver service

---

Dockerfile.dapper
images/10-openvmtools/Dockerfile
images/10-openvmtools/prebuild.sh

Reduce os-openvmtools size
`180M --> 70M`

Reduce os-openvmtools size

---

images/10-openvmtools/Dockerfile
images/10-openvmtools/prebuild.sh

This PR will fix https://github.com/rancher/os/issues/2371
Need re-publish `rancher/os-openvmtools:10.2.5-2`
Need re-build `rancheros-vmware.iso`

Add vmware-tools directory & default vmware scripts

---

a/alpine.yml
c/centos.yml
d/debian.yml
f/fedora.yml
images/10-alpineconsole/Dockerfile
images/10-centosconsole/Dockerfile
images/10-fedoraconsole/Dockerfile
images/10-ubuntuconsole/Dockerfile
u/ubuntu.yml

https://github.com/rancher/os/issues/2493

Console images update

---

images/20-iscsi/wonka.sh

Update the bind mount for iscsi-tools
Revert commit 0ca9b6de12de5b0158604b0b589cbae7f75c08d6

Fix bugs about iscsi service

---

images/10-centosconsole/Dockerfile
images/10-fedoraconsole/Dockerfile

Add scp support for centos and fedora consoles
https://github.com/rancher/os/issues/2536

Centos and fedora console support scp

---

images/10-alpineconsole/Dockerfile
images/10-debianconsole/Dockerfile
images/10-ubuntuconsole/Dockerfile

For alpine/debian/ubuntu console to add ` docker top ` support
https://github.com/rancher/os/issues/2340

Add  `docker top` support

---

images/10-modemmanager/Dockerfile
images/10-modemmanager/modemmanager
images/10-modemmanager/prebuild.sh
index.yml
m/modem-manager.yml

Add ModemManager service

---

images/10-waagent/Dockerfile
images/10-waagent/prebuild.sh
index.yml
w/waagent.yml

Add azure waagent

---

d/docker-18.09.0.yml
images/10-docker-18.09.0/Dockerfile
images/10-docker-18.09.0/prebuild.sh
images/10-docker-18.09.0_arm64/Dockerfile
images/10-docker-18.09.0_arm64/prebuild.sh
index.yml

Add docker-18.09.0

---

images/10-qemuguestagent/Dockerfile
q/qemu-guest-agent.yml

https://github.com/rancher/os/issues/2621

Fix qemu-guest-agent image for Promox VE

---

images/10-qemuguestagent/run

The docker user password is only modified when it is first started

The docker user password is only modified when it is first started

---

d/docker-18.09.1.yml
images/10-docker-18.09.1/Dockerfile
images/10-docker-18.09.1/prebuild.sh
images/10-docker-18.09.1_arm64/Dockerfile
images/10-docker-18.09.1_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2601

Add docker 18.09.1

---

r/rancher-server-stable.yml

https://github.com/rancher/os/issues/2686

Fix an issue where rancher-server-stable cannot be enabled

---

d/docker-18.06.3.yml
d/docker-18.09.3.yml
images/10-docker-18.06.3/Dockerfile
images/10-docker-18.06.3/prebuild.sh
images/10-docker-18.06.3_arm64/Dockerfile
images/10-docker-18.06.3_arm64/prebuild.sh
images/10-docker-18.09.3/Dockerfile
images/10-docker-18.09.3/prebuild.sh
images/10-docker-18.09.3_arm64/Dockerfile
images/10-docker-18.09.3_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2705

Add Docker 18.06.3 and Docker 18.09.3

---

images/10-alpineconsole/Dockerfile

I have tested on ARM and X86  and it works fine.
https://github.com/rancher/os/issues/2671

Upgrade alpine console to 3.9

---

images/10-centosconsole/Dockerfile
images/10-debianconsole/Dockerfile
images/10-fedoraconsole/Dockerfile
images/10-ubuntuconsole/Dockerfile

https://github.com/rancher/os/issues/2720

Add 'ping' 'curl' and 'wget' commands to other consoles

---

d/docker-18.09.4.yml
images/10-docker-18.09.4/Dockerfile
images/10-docker-18.09.4/prebuild.sh
images/10-docker-18.09.4_arm64/Dockerfile
images/10-docker-18.09.4_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2731

Add Docker 18.09.4

---

d/docker-18.09.5.yml
images/10-docker-18.09.5/Dockerfile
images/10-docker-18.09.5/prebuild.sh
images/10-docker-18.09.5_arm64/Dockerfile
images/10-docker-18.09.5_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2738

Add Docker 18.09.5

---

images/20-zfs/Dockerfile
images/20-zfs/Dockerfile.zfs-tools
images/20-zfs/build.sh
z/zfs.yml

rancher/os#2673
```shell
ros service enable zfs
ros service up zfs
zpool create zpool1 -m /mnt/zpool1 /dev/xxx
zfs create -V 128M -s zpool1/zvol
```
```shell
[root@rancher-dev rancher]# ls /dev/zvol
zpool1
```

Add zfs-helpers

---

d/docker-18.09.6.yml
images/10-docker-18.09.6/Dockerfile
images/10-docker-18.09.6/prebuild.sh
images/10-docker-18.09.6_arm64/Dockerfile
images/10-docker-18.09.6_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2761

Add Docker 18.09.6

---

images/10-fedoraconsole/Dockerfile

Remove duplicate sshd property from fedora console

---

h/hyperv-vm-tools.yml
images/10-hypervvmtools/Dockerfile
images/10-vboxtools/Dockerfile
v/virtualbox-tools.yml

https://github.com/rancher/os/issues/2818

Bump up kernel to 4.14.128-rancher

---

d/docker-18.09.8.yml
images/10-docker-18.09.8/Dockerfile
images/10-docker-18.09.8/prebuild.sh
images/10-docker-18.09.8_arm64/Dockerfile
images/10-docker-18.09.8_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2838

Add Docker 18.09.8

---

d/docker-19.03.0.yml
d/docker-19.03.1.yml
images/10-docker-19.03.0/Dockerfile
images/10-docker-19.03.0/prebuild.sh
images/10-docker-19.03.0_arm64/Dockerfile
images/10-docker-19.03.0_arm64/prebuild.sh
images/10-docker-19.03.1/Dockerfile
images/10-docker-19.03.1/prebuild.sh
images/10-docker-19.03.1_arm64/Dockerfile
images/10-docker-19.03.1_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2850

Add docker 19.03.0 and 19.03.1

---

d/docker-18.09.9.yml
images/10-docker-18.09.9/Dockerfile
images/10-docker-18.09.9/prebuild.sh
images/10-docker-18.09.9_arm64/Dockerfile
images/10-docker-18.09.9_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2886

Add Docker 18.09.9

---

d/docker-19.03.2.yml
images/10-docker-19.03.2/Dockerfile
images/10-docker-19.03.2/prebuild.sh
images/10-docker-19.03.2_arm64/Dockerfile
images/10-docker-19.03.2_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2884

Add Docker 19.03.2

---

a/alpine.yml
images/10-alpineconsole/Dockerfile

https://github.com/rancher/os/issues/2892

Bump alpine base image to 3.10

---

d/docker-19.03.3.yml
images/10-docker-19.03.3/Dockerfile
images/10-docker-19.03.3/prebuild.sh
images/10-docker-19.03.3_arm64/Dockerfile
images/10-docker-19.03.3_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2909

Add Docker 19.03.3

---

d/docker-19.03.4.yml
images/10-docker-19.03.4/Dockerfile
images/10-docker-19.03.4/prebuild.sh
images/10-docker-19.03.4_arm64/Dockerfile
images/10-docker-19.03.4_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2914

Add Docker 19.03.4

---

c/container-cron.yml

Updated container-cron to 0.5 and Docker API version to 1.24.

Updated container-cron to 0.5 and Docker API version to 1.24

---

d/docker-19.03.7.yml
images/10-docker-19.03.7/Dockerfile
images/10-docker-19.03.7/prebuild.sh
images/10-docker-19.03.7_arm64/Dockerfile
images/10-docker-19.03.7_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2969

Add Docker 19.03.7

---

d/docker-19.03.8.yml
images/10-docker-19.03.8/Dockerfile
images/10-docker-19.03.8/prebuild.sh
images/10-docker-19.03.8_arm64/Dockerfile
images/10-docker-19.03.8_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/2974

Add Docker 19.03.8

---

d/docker-19.03.9.yml
images/10-docker-19.03.9/Dockerfile
images/10-docker-19.03.9/prebuild.sh
images/10-docker-19.03.9_arm64/Dockerfile
images/10-docker-19.03.9_arm64/prebuild.sh
index.yml

https://github.com/rancher/os/issues/3002

Add Docker 19.03.9

---

d/docker-19.03.11.yml
images/10-docker-19.03.11/Dockerfile
images/10-docker-19.03.11/prebuild.sh
images/10-docker-19.03.11_arm64/Dockerfile
images/10-docker-19.03.11_arm64/prebuild.sh
index.yml

Docker [19.03.11](https://github.com/docker/docker-ce/releases/tag/v19.03.11) has been released.
Relates https://github.com/rancher/os/issues/3009.

Add Docker 19.03.11
